<a href="https://colab.research.google.com/github/fauzi122/ahmad123/blob/master/Salinan_dari_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Matriks

matriksA = np.array([[1,2],
                     [2,1]])
matriksB = np.array([[2,2],
                     [1,1]])   

perkalian_biasa = matriksA*matriksB

perkalian_matriks1 = np.dot(matriksA,matriksB)
perkalian_matriks2 = matriksA.dot(matriksB)

print("Matriks A :")
print(matriksA)

print("Matriks B :")
print(matriksB)

print("Perkalian Biasa Matriks : ")
print(perkalian_biasa)

Matriks A :
[[1 2]
 [2 1]]
Matriks B :
[[2 2]
 [1 1]]
Perkalian Biasa Matriks : 
[[2 4]
 [2 1]]


In [2]:
import pandas as pd

list_nim = []
list_nama = []
list_uts = []
list_uas = []
list_total = []

ulang = 2

for i in range(ulang):
    print("Data Ke : " + str(i+1))
    list_nim.append(input("Nim : "))
    list_nama.append(input("Nama : "))
    list_uts.append(int(input("Nilai UTS : ")))
    list_uas.append(int(input("Nilai UAS : ")))

for i in range(ulang):
    list_total.append((list_uts[i] + list_uas[i]) / 2)

mhs = {
    "NIM": list_nim,
    "Nama Lengkap": list_nama,
    "Nilai UTS": list_uts,
    "Nilai UAS": list_uas,
    "Rata - rata Nilai": list_total
}

data_mhs = pd.DataFrame(mhs)

print("====================================Daftar Nilai Mahasiswa====================================")
print(data_mhs)
print("==============================================================================================")


Data Ke : 1
Nim : 111
Nama : fauzi
Nilai UTS : 10
Nilai UAS : 10
Data Ke : 2
Nim : 10
Nama : fauzi
Nilai UTS : 100
Nilai UAS : 100
====================================Daftar Nilai Mahasiswa====================================
   NIM Nama Lengkap  Nilai UTS  Nilai UAS  Rata - rata Nilai
0  111        fauzi         10         10               10.0
1   10        fauzi        100        100              100.0
